name: "Generate CV"

on:
  push:
    branches:
      - main

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: chmod +x .github/workflows/package_install.sh && .github/workflows/package_install.sh
      - name: Generate english and greek pdfs
        run: chmod +x .github/workflows/generate_cv.sh && .github/workflows/generate_cv.sh
      - name: Publish CVs
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            cdalamagkas-cv-gr.pdf
            cdalamagkas-cv-en.pdf
          repo_token: ${{ secrets.GITHUB_TOKEN }}
