name: "Generate CV"

on:
  push:
    branches:
      - main

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: chmod +x .github/workflows/package_install.sh && .github/workflows/package_install.sh
      - name: Generate english and greek pdfs
        run: chmod +x .github/workflows/generate_cv.sh && .github/workflows/generate_cv.sh
      - name: Publish CVs
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: "cdalamagkas-cv-gr.pdf,cdalamagkas-cv-en.pdf"
          artifactContentType: "application/pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
